# Comparison Report Demo

- **Muc tieu:** Tuan 7-8 — sinh bao cao so sanh + citation
- **Nguyen tac:** _Khong bang chung -> khong ket luan_
- **Du lieu:** 2 file DOCX/PDF (sample v1 va v2)

Pipeline: **DOCX/PDF** → Read → Normalize → Chunk → Embedding → So sanh LLM → Bao cao

Notebook nay thuc hien full pipeline tu file goc (DOCX/PDF) den bao cao so sanh co trich dan.

In [3]:
# === Cell 2: Imports + Config (production-aligned) ===
import sys
import re
import os
import json
import difflib
from pathlib import Path
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
from IPython.display import HTML, display
from dotenv import load_dotenv

try:
    from rank_bm25 import BM25Okapi
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'rank-bm25', '-q'])
    from rank_bm25 import BM25Okapi

try:
    import ollama
except ImportError:
    ollama = None

ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.insert(0, str(ROOT))

DOC_DIR = ROOT / 'data' / 'document'
OUTPUT_DIR = ROOT / 'outputs'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Tu dong tim cap file de notebook khong vo do hard-code ten file
preferred_pair = DOC_DIR / 'pair 3'
pair_dirs = [preferred_pair] + [p for p in sorted(DOC_DIR.glob('pair *')) if p != preferred_pair]
PAIR_DIR = next((p for p in pair_dirs if p.exists() and any(p.glob('*.docx'))), None)
assert PAIR_DIR is not None, f'Khong tim thay thu muc pair co DOCX trong {DOC_DIR}'

candidates = [*PAIR_DIR.glob('*.docx'), *PAIR_DIR.glob('*.pdf')]
candidates = [f for f in candidates if 'changes' not in f.name.lower() and not f.name.startswith('~$')]
assert len(candidates) >= 2, f'Can it nhat 2 file hop le trong {PAIR_DIR}'

sorted_candidates = sorted(candidates, key=lambda p: ('v2' not in p.stem.lower(), p.name.lower()))
FILE_V2 = next((f for f in sorted_candidates if 'v2' in f.stem.lower()), sorted_candidates[1])
FILE_V1 = next((f for f in sorted_candidates if f != FILE_V2), sorted_candidates[0])

LLM_MODEL = 'qwen2.5:7b-instruct-q4_K_M'
EMBED_MODEL = 'huyydangg/DEk21_hcmute_embedding'

# Hybrid matching thresholds
COSINE_HIGH = 0.85
COSINE_LOW = 0.50
COSINE_WEIGHT = 0.70
BM25_WEIGHT = 0.30

load_dotenv(ROOT / '.env')
assert FILE_V1.exists(), f'Khong tim thay {FILE_V1}'
assert FILE_V2.exists(), f'Khong tim thay {FILE_V2}'

print(f'[OK] Pair dir      : {PAIR_DIR.name}')
print(f'[OK] V1            : {FILE_V1.name}')
print(f'[OK] V2            : {FILE_V2.name}')
print(f'[CFG] LLM model    : {LLM_MODEL}')
print(f'[CFG] Embed model  : {EMBED_MODEL}')
print(f'[CFG] cosine_high  : {COSINE_HIGH}  |  cosine_low : {COSINE_LOW}')
print(f'[CFG] weights      : cosine={COSINE_WEIGHT}, bm25={BM25_WEIGHT}')

[OK] Pair dir      : pair 3
[OK] V1            : Hợp Đồng Liên Doanh (thành lập công ty Logistics).docx
[OK] V2            : Hợp Đồng Liên Doanh (thành lập công ty Logistics)_V2.docx
[CFG] LLM model    : qwen2.5:7b-instruct-q4_K_M
[CFG] Embed model  : huyydangg/DEk21_hcmute_embedding
[CFG] cosine_high  : 0.85  |  cosine_low : 0.5
[CFG] weights      : cosine=0.7, bm25=0.3

In [ ]:
# === Cell 3: Read DOCX/PDF → Normalize → Chunk theo Khoản ===
import zipfile
import xml.etree.ElementTree as ET
from collections import defaultdict
from datetime import datetime, timezone

from docx import Document
import pdfplumber

# ── DOCX XML reading ──────────────────────────────────────────────────
W_URI = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
W_NS  = {"w": W_URI}

def _w_attr(name):
    return f"{{{W_URI}}}{name}"

def _read_docx_xml(path, inner_path):
    with zipfile.ZipFile(path) as zf:
        try:
            data = zf.read(inner_path)
        except KeyError:
            return None
    return ET.fromstring(data)

def _parse_docx_style_map(path):
    tree = _read_docx_xml(path, "word/styles.xml")
    if tree is None:
        return {}
    styles = {}
    for style in tree.findall(".//w:style", W_NS):
        style_id = style.get(_w_attr("styleId"))
        if not style_id:
            continue
        name_el      = style.find("w:name", W_NS)
        based_on_el  = style.find("w:basedOn", W_NS)
        num_pr       = style.find("w:pPr/w:numPr", W_NS)
        num_id, ilvl = None, None
        if num_pr is not None:
            nid_el = num_pr.find("w:numId", W_NS)
            il_el  = num_pr.find("w:ilvl", W_NS)
            if nid_el is not None: num_id = nid_el.get(_w_attr("val"))
            if il_el  is not None: ilvl   = il_el.get(_w_attr("val"))
        styles[style_id] = {
            "style_id":   style_id,
            "style_name": name_el.get(_w_attr("val")) if name_el is not None else style_id,
            "based_on":   based_on_el.get(_w_attr("val")) if based_on_el is not None else None,
            "num_id":     int(num_id) if num_id is not None else None,
            "ilvl":       int(ilvl)   if ilvl   is not None else None,
        }
    return styles

def _resolve_style_numbering(style_id, style_map, seen=None):
    if not style_id or style_id not in style_map:
        return None, None
    seen = seen or set()
    if style_id in seen:
        return None, None
    seen.add(style_id)
    info = style_map[style_id]
    if info["num_id"] is not None:
        return info["num_id"], info["ilvl"] if info["ilvl"] is not None else 0
    return _resolve_style_numbering(info["based_on"], style_map, seen)

def _parse_docx_numbering(path):
    tree = _read_docx_xml(path, "word/numbering.xml")
    numbering = {"num_to_abstract": {}, "abstract_levels": {}}
    if tree is None:
        return numbering
    for abstract in tree.findall("w:abstractNum", W_NS):
        abstract_id = abstract.get(_w_attr("abstractNumId"))
        if abstract_id is None:
            continue
        levels = {}
        for lvl in abstract.findall("w:lvl", W_NS):
            ilvl_raw = lvl.get(_w_attr("ilvl"))
            if ilvl_raw is None:
                continue
            start_el = lvl.find("w:start",   W_NS)
            fmt_el   = lvl.find("w:numFmt",  W_NS)
            text_el  = lvl.find("w:lvlText", W_NS)
            levels[int(ilvl_raw)] = {
                "start":    int(start_el.get(_w_attr("val"))) if start_el is not None else 1,
                "num_fmt":  fmt_el.get(_w_attr("val"))  if fmt_el  is not None else "decimal",
                "lvl_text": text_el.get(_w_attr("val")) if text_el is not None else f"%{int(ilvl_raw)+1}",
            }
        numbering["abstract_levels"][int(abstract_id)] = levels
    for num in tree.findall("w:num", W_NS):
        num_id     = num.get(_w_attr("numId"))
        abstract_el = num.find("w:abstractNumId", W_NS)
        if num_id is None or abstract_el is None:
            continue
        numbering["num_to_abstract"][int(num_id)] = int(abstract_el.get(_w_attr("val")))
    return numbering

def _to_roman(value):
    pairs = [(1000,"M"),(900,"CM"),(500,"D"),(400,"CD"),(100,"C"),(90,"XC"),
             (50,"L"),(40,"XL"),(10,"X"),(9,"IX"),(5,"V"),(4,"IV"),(1,"I")]
    result, remaining = [], max(1, value)
    for arabic, roman in pairs:
        while remaining >= arabic:
            result.append(roman); remaining -= arabic
    return "".join(result)

def _to_alpha(value, uppercase=False):
    chars, remaining = [], max(1, value)
    while remaining > 0:
        remaining -= 1
        chars.append(chr(ord("A" if uppercase else "a") + (remaining % 26)))
        remaining //= 26
    return "".join(reversed(chars))

def _format_counter(value, num_fmt):
    if num_fmt in {"upperRoman", "romanUpper"}:  return _to_roman(value)
    if num_fmt in {"lowerRoman", "romanLower"}:  return _to_roman(value).lower()
    if num_fmt == "upperLetter":                 return _to_alpha(value, True)
    if num_fmt == "lowerLetter":                 return _to_alpha(value, False)
    return str(value)

def _render_numbering_label(num_id, ilvl, numbering_data, counters_by_num):
    abstract_id = numbering_data["num_to_abstract"].get(num_id)
    levels      = numbering_data["abstract_levels"].get(abstract_id, {}) if abstract_id is not None else {}
    level_info  = levels.get(ilvl, {})
    counters    = counters_by_num[num_id]
    start       = level_info.get("start", 1)
    counters[ilvl] = counters.get(ilvl, start - 1) + 1
    for level in list(counters):
        if level > ilvl:
            del counters[level]
    label = level_info.get("lvl_text", f"%{ilvl + 1}")
    for level in range(ilvl + 1):
        if level not in counters:
            continue
        num_fmt   = levels.get(level, {}).get("num_fmt", "decimal")
        formatted = _format_counter(counters[level], num_fmt)
        label     = label.replace(f"%{level + 1}", formatted)
    return re.sub(r"\s+", " ", label).strip(), []

def _extract_paragraph_numbering(paragraph):
    p_pr   = paragraph._p.pPr
    num_pr = p_pr.numPr if p_pr is not None else None
    if num_pr is None:
        return None, None
    num_id_el, ilvl_el = num_pr.numId, num_pr.ilvl
    return (int(num_id_el.val) if num_id_el is not None else None,
            int(ilvl_el.val)   if ilvl_el   is not None else 0)

def _get_heading_level(style_name, style_id):
    for candidate in (style_name, style_id):
        if not candidate:
            continue
        normalized = re.sub(r"\s+", "", candidate).lower()
        if normalized.startswith("heading") and normalized[7:].isdigit():
            return int(normalized[7:])
    return None

def read_docx_document(path):
    doc             = Document(path)
    style_map       = _parse_docx_style_map(path)
    numbering_data  = _parse_docx_numbering(path)
    counters_by_num = defaultdict(dict)
    paragraphs = []
    for idx, paragraph in enumerate(doc.paragraphs):
        text = paragraph.text.strip()
        if not text:
            continue
        style_name    = paragraph.style.name     if paragraph.style else None
        style_id      = paragraph.style.style_id if paragraph.style else None
        heading_level = _get_heading_level(style_name, style_id)
        num_id, ilvl  = _extract_paragraph_numbering(paragraph)
        if num_id is None:
            num_id, ilvl = _resolve_style_numbering(style_id, style_map)
        numbering_label, numbering_path = None, []
        if num_id is not None and ilvl is not None:
            numbering_label, numbering_path = _render_numbering_label(
                num_id, ilvl, numbering_data, counters_by_num)
        display_text = text
        if heading_level in {1, 2, 3} and numbering_label:
            display_text = f"{numbering_label} {text}".strip()
        paragraphs.append({
            "idx": idx, "text": text, "display_text": display_text,
            "style_name": style_name, "style_id": style_id,
            "heading_level": heading_level, "num_id": num_id, "ilvl": ilvl,
            "numbering_label": numbering_label, "numbering_path": numbering_path,
        })
    return {"kind": "docx", "text": "\n".join(p["display_text"] for p in paragraphs), "paragraphs": paragraphs}

def read_pdf_text(path):
    pages = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:
                pages.append(text.strip())
    return "\n".join(pages)

def read_document(path):
    ext = path.suffix.lower()
    if ext == ".docx":
        return read_docx_document(path)
    if ext == ".pdf":
        text = read_pdf_text(path)
        paragraphs = [
            {"idx": i, "text": l.strip(), "display_text": l.strip(),
             "style_name": None, "style_id": None, "heading_level": None,
             "num_id": None, "ilvl": None, "numbering_label": None, "numbering_path": []}
            for i, l in enumerate(text.splitlines()) if l.strip()
        ]
        return {"kind": "pdf", "text": text, "paragraphs": paragraphs}
    raise ValueError(f"Không hỗ trợ định dạng: {ext}")

# ── Normalize ─────────────────────────────────────────────────────────
def normalize_text(text):
    text = text.replace("\xa0", " ")
    text = re.sub(r"\r\n|\r", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

def normalize_document(document):
    if isinstance(document, str):
        return normalize_text(document)
    paragraphs = []
    for para in document.get("paragraphs", []):
        text         = normalize_text(para.get("text", ""))
        display_text = normalize_text(para.get("display_text") or text)
        if not display_text:
            continue
        normalized = dict(para)
        normalized["text"]         = text
        normalized["display_text"] = display_text
        paragraphs.append(normalized)
    return {**document, "paragraphs": paragraphs,
            "text": "\n".join(p["display_text"] for p in paragraphs)}

# ── Chunk theo Khoản (đồng bộ Ingestion pipeline) ────────────────────
DIEU_RE       = re.compile(r"^(?:Điều|ĐIỀU|dieu|DIEU)\s+((?:\d+[A-Za-z]?|[IVXLCDM]+))[\.:]?\s*(.*)$")
KHOAN_RE      = re.compile(r"^(\d+(?:\.\d+)*)(?:[\.)])\s*(.*)$")
CHUONG_MUC_RE = re.compile(r"^(?:Chương|CHƯƠNG|Mục|MỤC|Phần|PHẦN)\s+")

def _make_chunk(chunk_idx, doc_id, version, article_number, article_title, khoan_number, lines):
    text = "\n".join(l for l in lines if l.strip()).strip()
    if not text:
        return None
    return {
        "chunk_id":       f"{doc_id}__{version}_chunk{chunk_idx:04d}",
        "doc_id":         doc_id,
        "version":        version,
        "article_number": str(article_number),
        "article_title":  article_title,
        "khoan_number":   str(khoan_number),
        "text":           text,
        "char_len":       len(text),
        "created_at":     datetime.now(timezone.utc).isoformat(),
    }

def _chunk_docx_headings_khoan(document, doc_id, version):
    """Chunk DOCX theo Khoản — đồng bộ Ingestion pipeline."""
    paragraphs = document.get("paragraphs", [])
    chunks, chunk_idx = [], 1
    curr_article_number = None
    curr_article_title  = ""
    curr_khoan_number   = "0"
    curr_lines          = []

    def flush_current():
        nonlocal chunk_idx, curr_khoan_number, curr_lines
        chunk = _make_chunk(chunk_idx, doc_id, version,
                            curr_article_number, curr_article_title,
                            curr_khoan_number, curr_lines)
        if chunk:
            chunks.append(chunk)
            chunk_idx += 1
        curr_lines        = []
        curr_khoan_number = "0"

    for para in paragraphs:
        nl        = para.get("numbering_label", "") or ""
        text_part = para.get("text", "").strip()
        display_text = (nl + " " + text_part).strip() if nl else text_part
        if not display_text:
            continue

        heading_level = para.get("heading_level") or 0
        m_dieu = DIEU_RE.match(display_text)
        if heading_level == 1 or m_dieu:
            flush_current()
            if m_dieu:
                curr_article_number = m_dieu.group(1)
                curr_article_title  = m_dieu.group(2).strip()
            curr_khoan_number = "0"
            curr_lines = []
            continue

        if curr_article_number is None:
            continue
        if CHUONG_MUC_RE.match(display_text):
            continue

        m_khoan = KHOAN_RE.match(display_text)
        if heading_level == 3 or m_khoan:
            flush_current()
            if m_khoan:
                curr_khoan_number = m_khoan.group(1)
                after = m_khoan.group(2).strip()
                if after:
                    curr_lines.append(after)
            else:
                curr_khoan_number = "0"
            continue

        curr_lines.append(display_text)

    flush_current()
    return chunks

def _chunk_plain_text_khoan(text, doc_id, version):
    """Chunk plain text theo Khoản — đồng bộ Ingestion pipeline."""
    lines = [l for l in text.split("\n") if l.strip()]
    chunks, chunk_idx = [], 1
    curr_article_number = None
    curr_article_title  = ""
    curr_khoan_number   = "0"
    curr_lines          = []

    def flush_current():
        nonlocal chunk_idx, curr_khoan_number, curr_lines
        chunk = _make_chunk(chunk_idx, doc_id, version,
                            curr_article_number, curr_article_title,
                            curr_khoan_number, curr_lines)
        if chunk:
            chunks.append(chunk)
            chunk_idx += 1
        curr_lines        = []
        curr_khoan_number = "0"

    for line in lines:
        s = line.strip()
        if CHUONG_MUC_RE.match(s):
            continue
        m_dieu = DIEU_RE.match(s)
        if m_dieu:
            flush_current()
            curr_article_number = m_dieu.group(1)
            curr_article_title  = m_dieu.group(2).strip()
            curr_khoan_number   = "0"
            curr_lines          = []
            continue
        if curr_article_number is None:
            continue
        m_khoan = KHOAN_RE.match(s)
        if m_khoan:
            flush_current()
            curr_khoan_number = m_khoan.group(1)
            after = m_khoan.group(2).strip()
            if after:
                curr_lines.append(after)
            continue
        curr_lines.append(s)

    flush_current()
    return chunks

def chunk_full_hierarchy(document, doc_id, version):
    if isinstance(document, dict):
        paragraphs = document.get("paragraphs", [])
        has_headings = sum(1 for p in paragraphs
                          if p.get("heading_level") == 1 and p.get("numbering_label")) > 0
        if has_headings:
            return _chunk_docx_headings_khoan(document, doc_id, version)
        return _chunk_plain_text_khoan(document.get("text", ""), doc_id, version)
    return _chunk_plain_text_khoan(document, doc_id, version)

# ── Thực thi ──────────────────────────────────────────────────────────
raw_v1   = read_document(FILE_V1)
raw_v2   = read_document(FILE_V2)
print(f'[OK] V1: {raw_v1["kind"]}, {len(raw_v1["paragraphs"])} paragraphs')
print(f'[OK] V2: {raw_v2["kind"]}, {len(raw_v2["paragraphs"])} paragraphs')

clean_v1 = normalize_document(raw_v1)
clean_v2 = normalize_document(raw_v2)

chunks_v1 = chunk_full_hierarchy(clean_v1, doc_id=FILE_V1.stem, version='v1')
chunks_v2 = chunk_full_hierarchy(clean_v2, doc_id=FILE_V2.stem, version='v2')

articles_v1 = sorted(set(c['article_number'] for c in chunks_v1), key=lambda x: int(x) if x.isdigit() else 0)
articles_v2 = sorted(set(c['article_number'] for c in chunks_v2), key=lambda x: int(x) if x.isdigit() else 0)

print(f'\n[OK] Chunks v1: {len(chunks_v1)} khoản  |  {len(articles_v1)} điều')
print(f'[OK] Chunks v2: {len(chunks_v2)} khoản  |  {len(articles_v2)} điều')
print(f'\nMẫu khoản v1:')
for c in chunks_v1[:3]:
    print(f'  Điều {c["article_number"]} | Khoản {c["khoan_number"]} | {c["text"][:70]}...')

[OK] V1: docx, 120 paragraphs
[OK] V2: docx, 123 paragraphs

[OK] Chunks v1: 65 khoản  |  28 điều
[OK] Chunks v2: 65 khoản  |  27 điều

Mẫu khoản v1:
  Điều 1 | Khoản 1.1 | Trong hợp đồng này, khi ngữ cảnh yêu cầu, các từ và các cụm từ sau đây...
  Điều 1 | Khoản 1.1.1 | “Điều lệ” nghĩa là Điều lệ của Công ty (hoặc sự sửa đổi sau đó phù hợp...
  Điều 1 | Khoản 1.1.2 | “Hội đồng thành viên Công ty” nghĩa là hội đồng gồm các đại diện cho c...

In [ ]:
# === Cell 4: Embed chunks (in-memory, không cần ChromaDB) ===
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity as sk_cosine
from sentence_transformers import SentenceTransformer
from pyvi import ViTokenizer


def load_embedder():
    """Load SentenceTransformer với local_files_only fallback."""
    try:
        return SentenceTransformer(EMBED_MODEL, local_files_only=True)
    except Exception:
        return SentenceTransformer(EMBED_MODEL)


def embed_texts(texts, embedder):
    """Embed list of texts sau khi tokenize bằng ViTokenizer."""
    segmented = [ViTokenizer.tokenize(t.lower()) for t in texts]
    return embedder.encode(segmented, convert_to_numpy=True, show_progress_bar=True)


def cosine_matrix(query_vecs, doc_vecs):
    """Cosine similarity matrix [n_queries × n_docs]."""
    return sk_cosine(query_vecs, doc_vecs)


embedder = load_embedder()
print(f'[OK] Embedding model: {embedder.get_sentence_embedding_dimension()} dim')

print('Đang embed v1...')
vectors_v1 = embed_texts([c['text'] for c in chunks_v1], embedder)
print('Đang embed v2...')
vectors_v2 = embed_texts([c['text'] for c in chunks_v2], embedder)

print(f'[OK] Vectors v1: {vectors_v1.shape}')
print(f'[OK] Vectors v2: {vectors_v2.shape}')

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 790.35it/s, Materializing param=pooler.dense.weight]

[OK] Embedding model: 768 dim
Đang embed v1...

Batches: 100%|██████████| 3/3 [00:00<00:00,  6.66it/s]

Đang embed v2...

Batches: 100%|██████████| 3/3 [00:00<00:00,  8.02it/s]

[OK] Vectors v1: (65, 768)
[OK] Vectors v2: (65, 768)

In [5]:
# === Cell 5: Hybrid Match (BM25 + Cosine) + LLM Compare ở mức Khoản ===
#
# Sơ đồ quyết định:
#   Bước 1 — BM25 + Cosine trong cùng Điều → hybrid score → chọn khoản v2 tốt nhất
#   Bước 2 — Ngưỡng:
#     cosine ≥ COSINE_HIGH → matched   (LLM quyết unchanged/changed)
#     cosine ∈ [LOW, HIGH) → weak_match (LLM xét với cảnh báo)
#     cosine < COSINE_LOW  → no_match  → removed
#     Điều không có trong v2           → no_article → removed
#     Khoản v2 chưa được ghép          → added
#   Bước 3 — LLM xác định trạng thái cuối; fallback difflib nếu LLM fail

# ── BM25 helper ───────────────────────────────────────────────────────
def tokenize_bm25(text):
    return ViTokenizer.tokenize(text.lower()).split()


# ── Hybrid matching ────────────────────────────────────────────────────
def hybrid_match_khoan(chunks_v1, chunks_v2, vectors_v1, vectors_v2):
    """Ghép từng khoản v1 với khoản v2 tốt nhất trong cùng Điều."""
    v2_by_article = defaultdict(list)
    for i, c in enumerate(chunks_v2):
        v2_by_article[c['article_number']].append((i, c))

    pairs = []
    matched_v2_indices = set()

    for i1, c1 in enumerate(chunks_v1):
        art_no     = c1['article_number']
        candidates = v2_by_article.get(art_no, [])

        if not candidates:
            pairs.append({'v1': c1, 'v2': None, 'match_type': 'no_article',
                          'cosine_score': 0.0, 'bm25_score': 0.0, 'hybrid_score': 0.0})
            continue

        cand_global = [idx for idx, _ in candidates]
        cand_chunks = [c   for _, c  in candidates]
        cand_vecs   = vectors_v2[cand_global]

        # Cosine scores
        cosine_scores = cosine_matrix([vectors_v1[i1]], cand_vecs)[0]

        # BM25 scores (normalized to [0, 1])
        corpus_tok = [tokenize_bm25(c['text']) for c in cand_chunks]
        bm25       = BM25Okapi(corpus_tok)
        bm25_raw   = np.array(bm25.get_scores(tokenize_bm25(c1['text'])))
        bm25_max   = bm25_raw.max() if bm25_raw.max() > 0 else 1.0
        bm25_norm  = bm25_raw / bm25_max

        # Hybrid score
        hybrid    = COSINE_WEIGHT * cosine_scores + BM25_WEIGHT * bm25_norm
        best_idx  = int(hybrid.argmax())

        best_cosine = float(cosine_scores[best_idx])
        best_bm25   = float(bm25_norm[best_idx])
        best_hybrid = float(hybrid[best_idx])
        best_chunk  = cand_chunks[best_idx]
        best_global = cand_global[best_idx]

        if best_cosine >= COSINE_HIGH:
            match_type = 'matched'
        elif best_cosine >= COSINE_LOW:
            match_type = 'weak_match'
        else:
            match_type  = 'no_match'
            best_chunk  = None
            best_global = None

        if best_global is not None:
            matched_v2_indices.add(best_global)

        pairs.append({'v1': c1, 'v2': best_chunk, 'match_type': match_type,
                      'cosine_score': round(best_cosine, 4),
                      'bm25_score':   round(best_bm25, 4),
                      'hybrid_score': round(best_hybrid, 4)})

    # Khoản v2 chưa được ghép → added
    for i2, c2 in enumerate(chunks_v2):
        if i2 not in matched_v2_indices:
            pairs.append({'v1': None, 'v2': c2, 'match_type': 'added',
                          'cosine_score': 0.0, 'bm25_score': 0.0, 'hybrid_score': 0.0})

    return pairs


pairs        = hybrid_match_khoan(chunks_v1, chunks_v2, vectors_v1, vectors_v2)
match_counts = Counter(p['match_type'] for p in pairs)
print(f'[OK] Tổng cặp sau ghép: {len(pairs)}')
for mt, cnt in sorted(match_counts.items()):
    print(f'  {mt:<15}: {cnt}')


# ── LLM helpers ───────────────────────────────────────────────────────
# Map từ difflib opcode → tag chuẩn (changed / removed / added)
_DIFF_TAG_MAP = {'replace': 'changed', 'delete': 'removed', 'insert': 'added'}

def _nws(text):
    return re.sub(r'\s+', ' ', text or '').strip()

def _shorten(text, n=300):
    text = _nws(text)
    return text if len(text) <= n else text[:n - 3].rstrip() + '...'

def _status_from_texts(b, a):
    if b == a:  return 'unchanged'
    if b and a: return 'changed'
    if b:       return 'removed'
    return 'added'

def _parse_json(text):
    if not text:
        return None
    try:
        return json.loads(text.strip())
    except json.JSONDecodeError:
        pass
    m = re.search(r'\{[\s\S]*\}', text)
    if m:
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            pass
    return None

def _diff_evidence(before, after, max_items=3):
    """Tạo evidence từ difflib với tag chuẩn: changed / removed / added."""
    b, a = _nws(before or ''), _nws(after or '')
    if not b and not a:
        return []
    if not b:
        return [{'tag': 'added',   'before': '', 'after': _shorten(a)}]
    if not a:
        return [{'tag': 'removed', 'before': _shorten(b), 'after': ''}]
    evidence = []
    for opcode, i1, i2, j1, j2 in difflib.SequenceMatcher(None, b, a).get_opcodes():
        if opcode == 'equal':
            continue
        tag            = _DIFF_TAG_MAP.get(opcode, 'changed')
        before_excerpt = _shorten(b[max(0, i1 - 80):i2 + 80].strip()) if opcode != 'insert' else ''
        after_excerpt  = _shorten(a[max(0, j1 - 80):j2 + 80].strip()) if opcode != 'delete' else ''
        # Bỏ qua evidence item rỗng
        if not before_excerpt and not after_excerpt:
            continue
        evidence.append({'tag': tag, 'before': before_excerpt, 'after': after_excerpt})
        if len(evidence) >= max_items:
            break
    return evidence


def _clean_llm_evidence(raw_evidence, max_items=3):
    """Chuẩn hoá evidence từ LLM: normalize tags, lọc item rỗng."""
    valid = []
    for e in (raw_evidence or []):
        if not isinstance(e, dict):
            continue
        # Dùng 'or ""' để xử lý cả trường hợp null (None) từ LLM
        before = _nws(str(e.get('before') or ''))
        after  = _nws(str(e.get('after')  or ''))
        # Loại bỏ evidence hoàn toàn rỗng
        if not before and not after:
            continue
        # Normalize tag về chuẩn
        tag = str(e.get('tag') or 'changed')
        tag = _DIFF_TAG_MAP.get(tag, tag)  # delete→removed, insert→added
        if tag not in ('changed', 'removed', 'added'):
            tag = 'changed'
        valid.append({'tag': tag, 'before': _shorten(before), 'after': _shorten(after)})
        if len(valid) >= max_items:
            break
    return valid


def llm_compare_khoan(art_no, khoan_no, art_title, before_text, after_text, match_type):
    b_norm = _nws(before_text or '')
    a_norm = _nws(after_text  or '')

    # Trường hợp rõ ràng, không cần LLM
    if match_type in ('no_article', 'no_match') and b_norm and not a_norm:
        return {'status': 'removed', 'conclusion': 'Khoản bị loại bỏ trong v2.',
                'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}
    if match_type == 'added' and a_norm and not b_norm:
        return {'status': 'added', 'conclusion': 'Khoản mới được bổ sung trong v2.',
                'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}
    if b_norm == a_norm:
        return {'status': 'unchanged', 'conclusion': 'Nội dung không thay đổi.',
                'evidence': [], 'llm_used': False, 'grounded': True}

    weak_hint = '\nCHÚ Ý: Cặp này có độ tương đồng thấp; có thể không cùng khoản.' if match_type == 'weak_match' else ''

    prompt = f"""Bạn là trợ lý đối chiếu văn bản pháp lý. So sánh 2 phiên bản cùng một Khoản.{weak_hint}

QUY TẮC BẮT BUỘC:
1. Chỉ dùng nội dung trong "Khoản v1" và "Khoản v2". Không bổ sung kiến thức ngoài.
2. Trạng thái CHỈ được là: unchanged | changed | added | removed.
3. Nếu không có bằng chứng text rõ ràng → evidence để rỗng, conclusion: "Không đủ bằng chứng".
4. Trả về DUY NHẤT JSON hợp lệ, không thêm markdown hay giải thích.

SCHEMA:
{{"status":"unchanged|changed|added|removed","conclusion":"string","evidence":[{{"tag":"changed|added|removed","before":"string","after":"string"}}]}}

META: Điều {art_no} - {art_title} | Khoản {khoan_no}

Khoản v1:
{b_norm or '(không có)'}

Khoản v2:
{a_norm or '(không có)'}""".strip()

    if ollama is None:
        status   = _status_from_texts(b_norm, a_norm)
        evidence = _diff_evidence(b_norm, a_norm)
        return {'status': status, 'conclusion': 'Fallback rule-based (ollama chưa cài).',
                'evidence': evidence, 'llm_used': False, 'grounded': bool(evidence)}

    try:
        resp    = ollama.chat(model=LLM_MODEL,
                              messages=[{'role': 'user', 'content': prompt}],
                              options={'temperature': 0})
        content = (resp.get('message') or {}).get('content', '')
        parsed  = _parse_json(content)
        if not parsed:
            raise ValueError('LLM output không phải JSON hợp lệ')

        status     = parsed.get('status', '')
        if status not in ('unchanged', 'changed', 'added', 'removed'):
            status = _status_from_texts(b_norm, a_norm)
        conclusion = _nws(parsed.get('conclusion', ''))

        # Chuẩn hoá evidence từ LLM (lọc rỗng, normalize tags)
        evidence = _clean_llm_evidence(parsed.get('evidence'), max_items=3)

        # Nếu LLM bảo changed/added/removed nhưng không có evidence → fallback difflib
        if status != 'unchanged' and not evidence:
            evidence = _diff_evidence(b_norm, a_norm, max_items=2)
        if status == 'unchanged':
            conclusion = 'Nội dung không thay đổi.'
            evidence   = []

        grounded = bool(evidence) or status == 'unchanged'
        return {'status': status, 'conclusion': conclusion or f'Khoản {status}.',
                'evidence': evidence, 'llm_used': True, 'grounded': grounded}

    except Exception as exc:
        status   = _status_from_texts(b_norm, a_norm)
        evidence = _diff_evidence(b_norm, a_norm)
        return {'status': status,
                'conclusion': f'LLM fail ({type(exc).__name__}), fallback rule-based.',
                'evidence': evidence, 'llm_used': False, 'grounded': bool(evidence)}


# ── So sánh tất cả các cặp ────────────────────────────────────────────
print('\nĐang so sánh từng cặp Khoản...')
comparison_results = []

for pair in pairs:
    c1, c2    = pair['v1'], pair['v2']
    art_no    = (c1 or c2)['article_number']
    khoan_no  = (c1 or c2)['khoan_number']
    art_title = (c1 or c2)['article_title']

    llm = llm_compare_khoan(
        art_no=art_no, khoan_no=khoan_no, art_title=art_title,
        before_text=c1['text'] if c1 else None,
        after_text=c2['text']  if c2 else None,
        match_type=pair['match_type'],
    )

    comparison_results.append({
        'article_number': art_no,
        'khoan_number':   khoan_no,
        'article_title':  art_title,
        'match_type':     pair['match_type'],
        'cosine_score':   pair['cosine_score'],
        'bm25_score':     pair['bm25_score'],
        'hybrid_score':   pair['hybrid_score'],
        'status':         llm['status'],
        'conclusion':     llm['conclusion'],
        'evidence':       llm['evidence'],
        'grounded':       llm['grounded'],
        'llm_used':       llm['llm_used'],
        'v1_text':        c1['text'] if c1 else None,
        'v2_text':        c2['text'] if c2 else None,
    })

status_counts  = Counter(r['status']    for r in comparison_results)
grounded_count = sum(1 for r in comparison_results if r['grounded'])
llm_used_count = sum(1 for r in comparison_results if r['llm_used'])

print(f'[OK] Hoàn thành so sánh {len(comparison_results)} khoản')
for s in ['unchanged', 'changed', 'added', 'removed']:
    print(f'  {s:<12}: {status_counts.get(s, 0)}')
print(f'  grounded    : {grounded_count}')
print(f'  llm_used    : {llm_used_count}')

# Preview kết quả
{
    'total': len(comparison_results),
    'status_counts': dict(status_counts),
    'match_counts':  dict(match_counts),
}

NameError: name 'chunks_v1' is not defined

In [ ]:

# === Cell 6: Báo cáo kết quả so sánh ở mức Khoản ===
# Hệ quy chiếu: V1 (phiên bản gốc) → V2 (phiên bản mới)
#   changed = khoản có đối chiếu ở cả V1 và V2 nhưng nội dung thay đổi → hiển thị song song 1 dòng/khoản
#   added   = khoản MỚI trong V2, không tìm thấy đối chiếu trong V1
#   removed = khoản TỒN TẠI trong V1, không còn trong V2

def _short(text, n=80):
    text = re.sub(r'\s+', ' ', text or '').strip()
    return text if len(text) <= n else text[:n - 3] + '...'

# ── Tổng quan ─────────────────────────────────────────────────────────
print('=== TỔNG QUAN SO SÁNH (HYBRID BM25+COSINE + LLM) — Mức Khoản ===')
print(f"  Hệ quy chiếu : V1 (gốc) → V2 (mới)")
print(f"  Tổng khoản   : {len(comparison_results)}")
for s in ['unchanged', 'changed', 'added', 'removed']:
    print(f"  {s:<12} : {status_counts.get(s, 0)}")
print(f"  grounded     : {grounded_count}")
print(f"  llm_used     : {llm_used_count}")
print(f"  cosine_high={COSINE_HIGH}  cosine_low={COSINE_LOW}")
print(f"  weights: cosine={COSINE_WEIGHT}  bm25={BM25_WEIGHT}")

# ── Bảng tổng hợp: 1 dòng / khoản có thay đổi ────────────────────────
n_changed_total = sum(1 for r in comparison_results if r['status'] != 'unchanged')
print(f'\n=== CÁC KHOẢN CÓ THAY ĐỔI / THÊM / XOÁ ({n_changed_total} khoản) ===')

summary_df = pd.DataFrame([
    {
        'Điều':       r['article_number'],
        'Khoản':      r['khoan_number'],
        'Tiêu đề':    _short(r['article_title'], 40),
        'Match':      r['match_type'],
        'Cosine':     r['cosine_score'],
        'BM25':       r['bm25_score'],
        'Hybrid':     r['hybrid_score'],
        'Trạng thái': r['status'],
        'Grounded':   r['grounded'],
        'Kết luận':   _short(r['conclusion']),
    }
    for r in comparison_results
    if r['status'] != 'unchanged'
])
display(summary_df if not summary_df.empty else pd.DataFrame())

# ── Bảng 1: KHOẢN THAY ĐỔI — 1 dòng / khoản, song song V1 ↔ V2 ────────
# Mỗi khoản changed hiện đúng 1 dòng: toàn văn V1 bên trái, toàn văn V2 bên phải
n_changed = status_counts.get('changed', 0)
print(f'\n=== KHOẢN THAY ĐỔI SO VỚI V1 — Đối chiếu song song ({n_changed} khoản) ===')
print('  Mỗi dòng là một khoản; cột V1/V2 hiện toàn văn để so sánh trực tiếp.')

changed_rows = [
    {
        'Điều':        r['article_number'],
        'Khoản':       r['khoan_number'],
        'Tiêu đề':     _short(r['article_title'], 40),
        'Nội dung V1': _short(r['v1_text'] or '', 300),
        'Nội dung V2': _short(r['v2_text'] or '', 300),
        'Kết luận':    _short(r['conclusion']),
    }
    for r in comparison_results if r['status'] == 'changed'
]
changed_ev_df = pd.DataFrame(changed_rows)
display(changed_ev_df if not changed_ev_df.empty else pd.DataFrame({'(Không có khoản changed)': []}))

# ── Bảng 2: KHOẢN MỚI — có trong V2, không tìm thấy đối chiếu trong V1 ──
n_added = status_counts.get('added', 0)
print(f'\n=== KHOẢN MỚI TRONG V2 (không có đối chiếu trong V1) — {n_added} khoản ===')
print('  Nhìn từ V1: những khoản này được THÊM MỚI khi chuyển từ V1 → V2.')

added_rows = [
    {
        'Điều':        r['article_number'],
        'Khoản':       r['khoan_number'],
        'Tiêu đề':     _short(r['article_title'], 40),
        'Nội dung V2': _short(r['v2_text'] or '', 300),
    }
    for r in comparison_results if r['status'] == 'added'
]
added_df = pd.DataFrame(added_rows)
display(added_df if not added_df.empty else pd.DataFrame({'(Không có khoản added)': []}))

# ── Bảng 3: KHOẢN ĐÃ MẤT — có trong V1, không tìm thấy đối chiếu trong V2 ──
n_removed = status_counts.get('removed', 0)
print(f'\n=== KHOẢN MẤT ĐI TRONG V2 (tồn tại trong V1, không còn trong V2) — {n_removed} khoản ===')
print('  Nhìn từ V1: những khoản này BỊ LOẠI BỎ khi chuyển từ V1 → V2.')

removed_rows = [
    {
        'Điều':        r['article_number'],
        'Khoản':       r['khoan_number'],
        'Tiêu đề':     _short(r['article_title'], 40),
        'Nội dung V1': _short(r['v1_text'] or '', 300),
    }
    for r in comparison_results if r['status'] == 'removed'
]
removed_df = pd.DataFrame(removed_rows)
display(removed_df if not removed_df.empty else pd.DataFrame({'(Không có khoản removed)': []}))

# ── Lưu báo cáo JSON ──────────────────────────────────────────────────
report = {
    'config': {
        'file_v1':        FILE_V1.name,
        'file_v2':        FILE_V2.name,
        'reference':      'V1 là hệ quy chiếu (phiên bản gốc)',
        'llm_model':      LLM_MODEL,
        'method':         'Hybrid BM25 + Cosine → LLM tại mức Khoản',
        'principle':      'Không bằng chứng → không kết luận',
        'cosine_high':    COSINE_HIGH,
        'cosine_low':     COSINE_LOW,
        'cosine_weight':  COSINE_WEIGHT,
        'bm25_weight':    BM25_WEIGHT,
        'total_khoan':    len(comparison_results),
        'status_counts':  dict(status_counts),
        'grounded_count': grounded_count,
        'llm_used_count': llm_used_count,
    },
    'khoan_results': comparison_results,
}

REPORT_PATH = OUTPUT_DIR / 'sample_pair_khoan_hybrid_report.json'
REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'\n[OK] Đã lưu báo cáo: {REPORT_PATH}')

print('\n=== NGUYÊN TẮC XÁC ĐỊNH TRẠNG THÁI (V1 làm hệ quy chiếu) ===')
print('  changed : khoản V1 tìm được đối chiếu trong V2 (cosine ≥ ngưỡng) nhưng nội dung đã thay đổi.')
print('  added   : khoản chỉ có trong V2 — V1 không có khoản tương đồng đủ ngưỡng.')
print('  removed : khoản chỉ có trong V1 — V2 không có khoản tương đồng đủ ngưỡng.')

=== TỔNG QUAN SO SÁNH (HYBRID BM25+COSINE + LLM) — Mức Khoản ===
  Hệ quy chiếu : V1 (gốc) → V2 (mới)
  Tổng khoản   : 67
  unchanged    : 60
  changed      : 3
  added        : 2
  removed      : 2
  grounded     : 67
  llm_used     : 4
  cosine_high=0.85  cosine_low=0.5
  weights: cosine=0.7  bm25=0.3

=== CÁC KHOẢN CÓ THAY ĐỔI / THÊM / XOÁ (7 khoản) ===

,Điều,Khoản,Tiêu đề,Match,Cosine,BM25,Hybrid,Trạng thái,Grounded,Kết luận
0,4,4.1,Vốn và tiến độ góp vốn của các bên:,no_match,0.3222,-3.2788,-0.7581,removed,True,Khoản bị loại bỏ trong v2.
1,4,4.2,Vốn và tiến độ góp vốn của các bên:,matched,0.9680,-0.8519,0.4220,changed,True,Thời gian và lãi suất phạt thay đổi
2,5,5.1,HỘI Đồng Thành Viên,matched,0.9188,1.0000,0.9432,changed,True,Thay đổi về tần suất họp và nội dung được đánh...
3,5,5.3,HỘI Đồng Thành Viên,matched,0.9953,1.0000,0.9967,changed,True,Thay đổi từ 75% sang 80%
4,5B,0,IS. BAN GIÁM ĐỐC VÀ VIỆC ĐIỀU HÀNH HO...,no_article,0.0000,0.0000,0.0000,removed,True,Khoản bị loại bỏ trong v2.
5,4,4.1,Vốn và tiến độ góp vốn của các bên:,added,0.0000,0.0000,0.0000,added,True,Khoản mới được bổ sung trong v2.
6,5,0,BAN GIÁM ĐỐC VÀ VIỆC ĐIỀU HÀNH HOẠT Đ...,added,0.0000,0.0000,0.0000,added,True,Khoản mới được bổ sung trong v2.

=== KHOẢN THAY ĐỔI SO VỚI V1 — Đối chiếu song song (3 khoản) ===
  Mỗi dòng là một khoản; cột V1/V2 hiện toàn văn để so sánh trực tiếp.

,Điều,Khoản,Tiêu đề,Nội dung V1,Nội dung V2,Kết luận
0,4,4.2,Vốn và tiến độ góp vốn của các bên:,Xử lý góp vốn không đầy đủ và đúng tiến độ: Bấ...,Xử lý góp vốn không đầy đủ và đúng tiến độ: Bấ...,Thời gian và lãi suất phạt thay đổi
1,5,5.1,HỘI Đồng Thành Viên,Hội đồng thành viên sẽ họp ít nhất 03 tháng mộ...,Hội đồng thành viên sẽ họp ít nhất 02 tháng mộ...,Thay đổi về tần suất họp và nội dung được đánh...
2,5,5.3,HỘI Đồng Thành Viên,Cuộc họp của Hội đồng thành viên sẽ được tiến ...,Cuộc họp của Hội đồng thành viên sẽ được tiến ...,Thay đổi từ 75% sang 80%

=== KHOẢN MỚI TRONG V2 (không có đối chiếu trong V1) — 2 khoản ===
  Nhìn từ V1: những khoản này được THÊM MỚI khi chuyển từ V1 → V2.

,Điều,Khoản,Tiêu đề,Nội dung V2
0,4,4.1,Vốn và tiến độ góp vốn của các bên:,Vốn góp: vốn góp của công ty là 25.000.000 USD...
1,5,0,BAN GIÁM ĐỐC VÀ VIỆC ĐIỀU HÀNH HOẠT Đ...,5bis.1. Các bên góp vốn sẽ thảo luận để đạt đư...

=== KHOẢN MẤT ĐI TRONG V2 (tồn tại trong V1, không còn trong V2) — 2 khoản ===
  Nhìn từ V1: những khoản này BỊ LOẠI BỎ khi chuyển từ V1 → V2.

,Điều,Khoản,Tiêu đề,Nội dung V1
0,4,4.1,Vốn và tiến độ góp vốn của các bên:,Vốn góp : vốn góp của công ty là 20.000.000 US...
1,5B,0,IS. BAN GIÁM ĐỐC VÀ VIỆC ĐIỀU HÀNH HO...,5bis.1. Các bên góp vốn sẽ thảo luận để đạt đư...

[OK] Đã lưu báo cáo: d:\Data Self Learning\Extra Projects\rag-based-legal-comparison\outputs\sample_pair_khoan_hybrid_report.json

=== NGUYÊN TẮC XÁC ĐỊNH TRẠNG THÁI (V1 làm hệ quy chiếu) ===
  changed : khoản V1 tìm được đối chiếu trong V2 (cosine ≥ ngưỡng) nhưng nội dung đã thay đổi.
  added   : khoản chỉ có trong V2 — V1 không có khoản tương đồng đủ ngưỡng.
  removed : khoản chỉ có trong V1 — V2 không có khoản tương đồng đủ ngưỡng.

# Cell 7 — Thử nghiệm: Semantic Legal Judge (hướng "giống Claude")

Mục tiêu: kiểm chứng một hướng so sánh **mới** trước khi đưa vào `src/comparator.py`.

Khác biệt cốt lõi so với baseline (Cell 5):

|                   | Baseline (Cell 5)                               | Semantic Judge (Cell 7)                                                                           |
| ----------------- | ----------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| Vai trò `difflib` | Quyết định một phần status qua `_diff_evidence` | **Chỉ dùng để highlight UI**, không quyết định status                                             |
| Schema            | status + conclusion + evidence                  | + `change_type` (editorial / clarifying / substantive / reversal) + `severity` + `affected_party` |
| Khi JSON lỗi      | Rơi thẳng về rule-based difflib                 | **Retry 1 lần** với nhắc ngắn, rồi mới fallback                                                   |
| Tư duy            | So đoạn khác nhau theo ký tự                    | Để model **tự align + đánh giá nghĩa pháp lý**                                                    |

Cell này **không sửa** logic production. Nó chạy song song trên cùng `pairs`, rồi in **bảng bất đồng** (disagreement) giữa 2 phương pháp để bạn đánh giá thủ công.

In [ ]:
# === Cell 7: Semantic Legal Judge — chạy thử song song với baseline ===
# Tư tưởng: để LLM TỰ align + đánh giá NGHĨA pháp lý.
# difflib chỉ dùng để highlight (UI), KHÔNG quyết định status.

VALID_STATUS  = ('unchanged', 'changed', 'added', 'removed')
VALID_CHANGE  = ('none', 'editorial', 'clarifying', 'substantive', 'reversal')
VALID_SEVERITY = ('none', 'low', 'medium', 'high')

JUDGE_SYSTEM = (
    "Bạn là thẩm định viên đối chiếu văn bản pháp lý tiếng Việt. "
    "Nhiệm vụ: so sánh NGHĨA của hai phiên bản cùng một Khoản, không so sánh ký tự. "
    "Tự căn chỉnh (align) các mệnh đề tương ứng kể cả khi câu được diễn đạt lại "
    "hoặc đảo thứ tự. Chỉ dựa trên nội dung được cung cấp, không thêm kiến thức ngoài."
)

def _build_judge_prompt(art_no, khoan_no, art_title, b_norm, a_norm, retry_hint=""):
    return f"""So sánh hai phiên bản của cùng một Khoản pháp lý theo NGHĨA.{retry_hint}

QUY TẮC:
1. Tự align mệnh đề tương ứng giữa v1 và v2; bỏ qua khác biệt thuần hình thức
   (đảo thứ tự câu, viết lại nhưng giữ nguyên nghĩa) → coi là 'editorial' và status 'unchanged'.
2. Phân loại change_type:
   - none: không đổi nghĩa.
   - editorial: chỉ sửa câu chữ/diễn đạt, nghĩa giữ nguyên.
   - clarifying: làm rõ nhưng không đổi quyền/nghĩa vụ.
   - substantive: thay đổi quyền/nghĩa vụ/thời hạn/chế tài/phạm vi.
   - reversal: đảo ngược nghĩa (vd thêm/bỏ "không", "trừ trường hợp").
3. severity: none | low | medium | high theo mức ảnh hưởng pháp lý.
4. status suy ra từ nghĩa: unchanged nếu change_type∈{{none,editorial}}; ngược lại changed.
   Dùng added/removed chỉ khi một phía hoàn toàn không có nội dung tương ứng.
5. conclusion: 1-2 câu TIẾNG VIỆT, nêu rõ ĐIỀU GÌ đổi và HỆ QUẢ pháp lý.
6. evidence: trích cặp mệnh đề trước/sau đã align (tối đa 3).
7. CHỈ trả về JSON hợp lệ, không markdown, không giải thích thêm.

SCHEMA:
{{"status":"unchanged|changed|added|removed","change_type":"none|editorial|clarifying|substantive|reversal","severity":"none|low|medium|high","affected_party":"string","conclusion":"<tiếng Việt>","evidence":[{{"tag":"changed|added|removed","before":"string","after":"string"}}]}}

META: Điều {art_no} - {art_title} | Khoản {khoan_no}

Khoản v1:
{b_norm or '(không có)'}

Khoản v2:
{a_norm or '(không có)'}""".strip()


def _coerce_judge(parsed, b_norm, a_norm):
    """Chuẩn hoá output judge; suy ra status từ change_type khi cần."""
    change_type = str(parsed.get('change_type') or '').lower()
    if change_type not in VALID_CHANGE:
        change_type = ''
    severity = str(parsed.get('severity') or '').lower()
    if severity not in VALID_SEVERITY:
        severity = ''

    status = str(parsed.get('status') or '').lower()
    if status not in VALID_STATUS:
        status = ''

    # Suy status từ change_type khi status thiếu/không nhất quán
    if not status:
        if change_type in ('none', 'editorial'):
            status = 'unchanged'
        elif change_type in ('clarifying', 'substantive', 'reversal'):
            status = 'changed'
        else:
            status = _status_from_texts(b_norm, a_norm)
    # An toàn: nếu một phía rỗng thì added/removed thắng
    if b_norm and not a_norm:
        status = 'removed'
    elif a_norm and not b_norm:
        status = 'added'

    evidence = _clean_llm_evidence(parsed.get('evidence'), max_items=3)
    conclusion = _nws(parsed.get('conclusion') or '')
    affected = _nws(parsed.get('affected_party') or '')
    return status, change_type, severity, affected, conclusion, evidence


def judge_khoan(art_no, khoan_no, art_title, before_text, after_text, match_type):
    b_norm = _nws(before_text or '')
    a_norm = _nws(after_text  or '')

    # Trường hợp hiển nhiên — không cần LLM
    if b_norm == a_norm:
        return {'status': 'unchanged', 'change_type': 'none', 'severity': 'none',
                'affected_party': '', 'conclusion': 'Nội dung không thay đổi.',
                'evidence': [], 'llm_used': False, 'grounded': True}
    if b_norm and not a_norm:
        return {'status': 'removed', 'change_type': 'substantive', 'severity': 'high',
                'affected_party': '', 'conclusion': 'Khoản bị loại bỏ trong v2.',
                'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}
    if a_norm and not b_norm:
        return {'status': 'added', 'change_type': 'substantive', 'severity': 'high',
                'affected_party': '', 'conclusion': 'Khoản mới được bổ sung trong v2.',
                'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}

    if ollama is None:
        st = _status_from_texts(b_norm, a_norm)
        return {'status': st, 'change_type': '', 'severity': '', 'affected_party': '',
                'conclusion': 'Fallback rule-based (ollama chưa cài).',
                'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}

    # Gọi LLM, retry 1 lần nếu JSON lỗi (khác baseline: baseline rơi thẳng difflib)
    last_exc = None
    for attempt in range(2):
        retry_hint = "" if attempt == 0 else "\nLƯU Ý: Lần trước output KHÔNG phải JSON hợp lệ. Chỉ in JSON."
        prompt = _build_judge_prompt(art_no, khoan_no, art_title, b_norm, a_norm, retry_hint)
        try:
            resp = ollama.chat(model=LLM_MODEL,
                               messages=[{'role': 'system', 'content': JUDGE_SYSTEM},
                                         {'role': 'user', 'content': prompt}],
                               options={'temperature': 0})
            content = (resp.get('message') or {}).get('content', '')
            parsed = _parse_json(content)
            if not parsed:
                raise ValueError('LLM output không phải JSON hợp lệ')

            status, change_type, severity, affected, conclusion, evidence = \
                _coerce_judge(parsed, b_norm, a_norm)

            # difflib CHỈ để highlight khi LLM không nêu evidence (không đổi status)
            if status != 'unchanged' and not evidence:
                evidence = _diff_evidence(b_norm, a_norm, max_items=2)
            if status == 'unchanged':
                evidence = []
                conclusion = conclusion or 'Chỉ thay đổi hình thức, nghĩa không đổi.'

            grounded = bool(evidence) or status == 'unchanged'
            return {'status': status, 'change_type': change_type, 'severity': severity,
                    'affected_party': affected, 'conclusion': conclusion or f'Khoản {status}.',
                    'evidence': evidence, 'llm_used': True, 'grounded': grounded}
        except Exception as exc:
            last_exc = exc
            continue

    # Hết retry → fallback rule-based
    st = _status_from_texts(b_norm, a_norm)
    return {'status': st, 'change_type': '', 'severity': '', 'affected_party': '',
            'conclusion': f'LLM fail ({type(last_exc).__name__}) sau 2 lần, fallback rule-based.',
            'evidence': _diff_evidence(b_norm, a_norm), 'llm_used': False, 'grounded': True}


# ── Chạy judge trên cùng tập `pairs` ─────────────────────────────────
print('Đang chạy Semantic Legal Judge (thử nghiệm)...')
judge_results = []
for pair in pairs:
    c1, c2    = pair['v1'], pair['v2']
    art_no    = (c1 or c2)['article_number']
    khoan_no  = (c1 or c2)['khoan_number']
    art_title = (c1 or c2)['article_title']

    jr = judge_khoan(
        art_no=art_no, khoan_no=khoan_no, art_title=art_title,
        before_text=c1['text'] if c1 else None,
        after_text=c2['text']  if c2 else None,
        match_type=pair['match_type'],
    )
    judge_results.append({
        'article_number': art_no, 'khoan_number': khoan_no, 'article_title': art_title,
        'match_type': pair['match_type'], **jr,
        'v1_text': c1['text'] if c1 else None,
        'v2_text': c2['text'] if c2 else None,
    })

judge_status = Counter(r['status'] for r in judge_results)
print(f'[OK] Judge xong {len(judge_results)} khoản')
for s in VALID_STATUS:
    print(f'  {s:<12}: {judge_status.get(s, 0)}')
print('  change_type :', dict(Counter(r["change_type"] for r in judge_results)))
print('  severity    :', dict(Counter(r["severity"] for r in judge_results)))
print('  llm_used    :', sum(1 for r in judge_results if r['llm_used']))

In [ ]:
# === Cell 8: So sánh Baseline (Cell 5) vs Judge (Cell 7) ===
# In bảng các khoản mà 2 phương pháp BẤT ĐỒNG status để review thủ công.

base_by_key  = {(r['article_number'], r['khoan_number']): r for r in comparison_results}
judge_by_key = {(r['article_number'], r['khoan_number']): r for r in judge_results}
all_keys = sorted(set(base_by_key) | set(judge_by_key))

rows, n_disagree = [], 0
for key in all_keys:
    b = base_by_key.get(key)
    j = judge_by_key.get(key)
    b_status = b['status'] if b else '(missing)'
    j_status = j['status'] if j else '(missing)'
    disagree = b_status != j_status
    if disagree:
        n_disagree += 1
    rows.append({
        'Điều':         key[0],
        'Khoản':        key[1],
        'Tiêu đề':      _short((j or b)['article_title'], 36),
        'Baseline':     b_status,
        'Judge':        j_status,
        'change_type':  (j or {}).get('change_type', ''),
        'severity':     (j or {}).get('severity', ''),
        '≠':            '⚠️' if disagree else '',
        'KL Judge':     _short((j or {}).get('conclusion', ''), 70),
    })

cmp_df = pd.DataFrame(rows)

print('=== ĐỐI CHIẾU BASELINE vs SEMANTIC JUDGE ===')
print(f'  Tổng khoản     : {len(all_keys)}')
print(f'  Bất đồng status: {n_disagree}')
print(f'  Tỉ lệ đồng ý   : {(len(all_keys) - n_disagree) / max(1, len(all_keys)) * 100:.1f}%')

print('\n--- CHỈ CÁC KHOẢN BẤT ĐỒNG (cần review thủ công) ---')
disagree_df = cmp_df[cmp_df['≠'] == '⚠️'].drop(columns=['≠'])
display(disagree_df if not disagree_df.empty else pd.DataFrame({'(Hai phương pháp đồng ý hoàn toàn)': []}))

print('\n--- TOÀN BỘ BẢNG ĐỐI CHIẾU ---')
display(cmp_df)

# ── Lưu kết quả judge để đối chiếu ngoài notebook ────────────────────
JUDGE_PATH = OUTPUT_DIR / 'sample_pair_semantic_judge_report.json'
JUDGE_PATH.write_text(json.dumps({
    'method': 'Semantic Legal Judge (thử nghiệm) — align nghĩa, difflib chỉ để highlight',
    'llm_model': LLM_MODEL,
    'total_khoan': len(judge_results),
    'status_counts': dict(judge_status),
    'disagree_with_baseline': n_disagree,
    'khoan_results': judge_results,
}, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'\n[OK] Đã lưu: {JUDGE_PATH}')
print('\nGhi chú: review cột "≠"; nếu Judge đúng hơn baseline ở các ca substantive/reversal,')
print('         thì port logic này vào src/comparator.py (giữ difflib chỉ để highlight UI).')

## Production-aligned path (moi)

Cell ben duoi goi truc tiep `run_comparison_pipeline` tu src/pipeline.py.

Muc tieu:

- dong bo 100% voi backend API hien tai
- co reset collection moi lan chay
- dung filter mac dinh: bo dieu 0 va bo non-khoan

In [ ]:
# === Production Cell A: run_comparison_pipeline dung src/* ===
import os
import sys
import json
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.insert(0, str(ROOT))

from configs.defaults import OLLAMA_MODEL, EMBEDDING_MODEL, CHROMA_COLLECTION, COSINE_LOW
from src.pipeline import run_comparison_pipeline

OUTPUT_DIR = ROOT / 'outputs'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PAIR_DIR = ROOT / 'data' / 'document' / 'pair 3'

# Tu dong tim 2 file can so sanh trong pair 3
files = [*PAIR_DIR.glob('*.docx'), *PAIR_DIR.glob('*.pdf')]
files = [f for f in files if 'changes' not in f.name.lower() and not f.name.startswith('~$')]
assert len(files) >= 2, f'Can it nhat 2 file trong {PAIR_DIR}'

# uu tien file co "v2" lam file_v2
files_sorted = sorted(files, key=lambda p: ('v2' not in p.stem.lower(), p.name.lower()))
file_v2 = next((f for f in files_sorted if 'v2' in f.stem.lower()), files_sorted[1])
file_v1 = next((f for f in files_sorted if f != file_v2), files_sorted[0])

print(f'[OK] file_v1: {file_v1.name}')
print(f'[OK] file_v2: {file_v2.name}')
print('[INFO] Model load se mat thoi gian o lan dau (embed model)')

res = run_comparison_pipeline(
    file_v1=file_v1,
    file_v2=file_v2,
    chroma_dir=ROOT / 'chroma_db',
    output_dir=OUTPUT_DIR,
    llm_model=OLLAMA_MODEL,
    embed_model=EMBEDDING_MODEL,
    collection_name=CHROMA_COLLECTION,
    top_k=3,
    threshold=COSINE_LOW,
    hf_token=os.getenv('HF_TOKEN'),
    include_preamble=False,
    include_non_khoan=False,
)

prod_report = res['report']
prod_rows = prod_report.get('article_level_results', [])
prod_cfg = prod_report.get('config', {})

print('\n=== Production pipeline summary ===')
print(f"Total rows: {prod_cfg.get('total_khoans')}")
print('Status counts:', prod_cfg.get('status_counts', {}))
print(f"LLM used: {prod_cfg.get('llm_used_count')} | grounded: {prod_cfg.get('grounded_count')}")
print(f"Report JSON: {res['report_path']}")
print(f"Copilot JSON: {res['copilot_json_path']}")
print(f"Copilot TXT: {res['copilot_txt_path']}")

# Luu nhanh ra file de notebook khac co the dung lai
prod_path = OUTPUT_DIR / 'comparison_production_rows.json'
prod_path.write_text(json.dumps(prod_rows, ensure_ascii=False, indent=2), encoding='utf-8')
print(f"[OK] Saved rows snapshot: {prod_path}")

d:\Data Self Learning\Extra Projects\rag-based-legal-comparison\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\Data Self Learning\Extra Projects\rag-based-legal-comparison\.venv\Lib\site-packages\pyvi\ViTokenizer.py:24: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  model = pickle.load(fin)
2026-06-15 11:05:23.407 | INFO     | src.pipeline:_progress:90 - [0%] Doc va chuan hoa file v1...
2026-06-15 11:05:23.511 | INFO     | src.pipeline:_progress:90 - [10%] Doc va chuan hoa file v2...

[OK] file_v1: Hợp Đồng Liên Doanh (thành lập công ty Logistics).docx
[OK] file_v2: Hợp Đồng Liên Doanh (thành lập công ty Logistics)_V2.docx
[INFO] Model load se mat thoi gian o lan dau (embed model)

2026-06-15 11:05:23.646 | INFO     | src.pipeline:_progress:90 - [20%] Chia chunk v1 theo Dieu...
2026-06-15 11:05:23.648 | INFO     | src.pipeline:_progress:90 - [25%] Chia chunk v2 theo Dieu...
2026-06-15 11:05:23.649 | INFO     | src.pipeline:_progress:90 - [28%] Tach chunk theo Khoan...
2026-06-15 11:05:23.651 | INFO     | src.pipeline:run_comparison_pipeline:112 - Khoan chunks: v1=50, v2=52
2026-06-15 11:05:23.651 | INFO     | src.pipeline:_progress:90 - [30%] Tai embedding model...
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 740.99it/s, Materializing param=pooler.dense.weight]
2026-06-15 11:05:31.429 | INFO     | src.pipeline:_progress:90 - [40%] Index v1 vao ChromaDB...
Batches: 100%|██████████| 2/2 [00:00<00:00,  4.08it/s]
2026-06-15 11:05:32.117 | INFO     | src.pipeline:_progress:90 - [50%] Index v2 vao ChromaDB...
Batches: 100%|██████████| 2/2 [00:00<00:00,  9.10it/s]
2026-06-15 11:05:32.492 | INFO     | src.pipeline:run_comparison_pipeline:131 - Indexed: v1=50, v2=52
2026-06-15 11:05:32.493 | INFO     | src.pipeline:_progress:90 - [60%] So sanh cac Dieu bang vector retrieval + LLM...